### PR TITLE
Change to non-key API

### PR DESCRIPTION
**Pull request by KorewaLidesu**
Simple implement. You can pull if like it.
~~Thanks for the base, really impressive <3~~

### CODE REVIEW

**Comment by KorewaLidesu** [comment]
~~Hmmmm, I think it should be in different branch instead.
So user can have option, or maybe just no~~

**Comment by KorewaLidesu** [comment]
Change some docs as API changed.

**Comment by OwenCochell** [comment]
Does the curse.tools backend not require an API key? That's another good reason it get it implemented. I think we should implement this backend as new handlers, so users can use the official API if they want. I don't think it would be very hard, we can inherit most of the functionality as we just have to change the URL and remove the API key stuff. From what I understand curse.tools proxys everything to the official API, so it is functionaly the same. What do you think?

Unfortunately I'm not at my computer right now, and won't be for a bit, but I'll give everything a review once im back home. Apologies if I missed something, it's difficult to read this stuff on a small phone haha.

Thanks!

**Comment by KorewaLidesu** [comment]
> Does the curse.tools backend not require an API key? That's another good reason it get it implemented. I think we should implement this backend as new handlers, so users can use the official API if they want. I don't think it would be very hard, we can inherit most of the functionality as we just have to change the URL and remove the API key stuff. From what I understand curse.tools proxys everything to the official API, so it is functionaly the same. What do you think?

There isn't available docs rather than the url change on their page. But yes, their function both same ~~as you don't need to include API key in header~~. "Simplify"

**Comment by OwenCochell** [comment]
Apologies for the response delay, I will be creating new handlers for this backend and hopefully get it out today or tomorrow. I think making this change in a pull request is not a great idea as it is somewhat-big, so we can close this pull request if you want. I will post back here once that feature is implemented.

if you wish, I can add credit for your contribution in the readme, so you can still get credit for the work you have done so far, as this pull request will likely be closed. I'll do all the implementation on my end. Let me know if you have any comments on this strategy.

Thanks!

**Comment by KorewaLidesu** [comment]
> Apologies for the response delay, I will be creating new handlers for this backend and hopefully get it out today or tomorrow. I think making this change in a pull request is not a great idea as it is somewhat-big, so we can close this pull request if you want. I will post back here once that feature is implemented.

Oh yes, this pull request dont have anything to resolve so I gonna close it.
P/s: Thank you for continueing develope this xD

P/s2: About implement new handlers, maybe it better to make condition state instead, like if there is valid key available or not. 
<details>
<summary>spoiler</summary>
was gonna try it out but no knowledge with Python :x
</details>

**Pull request closed without merging**
